<a href="https://colab.research.google.com/github/roggersanguzu/ML-Datageddon/blob/main/Medic_Expenditure_Many_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Roggers Anguzu.
# Using multiple features
import matplotlib.pyplot as plt
import matplotlib as matplotlib
import seaborn as sns
import plotly.express as px
import numpy as np
import pandas as pd
%matplotlib inline

In [3]:
url = "https://raw.githubusercontent.com/roggersanguzu/Machine-Learning-with-R-datasets/master/insurance.csv"
medicdata = pd.read_csv(url)

In [4]:
sns.set_style("darkgrid")
matplotlib.rcParams['font.size']=14
matplotlib.rcParams['figure.figsize']=(10,5)

In [5]:
batch1=medicdata.copy()
batch2=medicdata.copy()
batch3=medicdata.copy()
batch4=medicdata.copy()

In [6]:
batch1['smoker'] = batch1['smoker'].str.strip().str.lower()
batch1['smoker'] = batch1['smoker'].map({'yes': 1, 'no': 0})
batch1

age     sex     bmi  children  smoker     region      charges
0      19  female  27.900         0       1  southwest  16884.92400
1      18    male  33.770         1       0  southeast   1725.55230
2      28    male  33.000         3       0  southeast   4449.46200
3      33    male  22.705         0       0  northwest  21984.47061
4      32    male  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
1333   50    male  30.970         3       0  northwest  10600.54830
1334   18  female  31.920         0       0  northeast   2205.98080
1335   18  female  36.850         0       0  southeast   1629.83350
1336   21  female  25.800         0       0  southwest   2007.94500
1337   61  female  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
smokers=batch1[batch1['smoker']==1]
nonsmoker=batch1[batch1['smoker']==0]

In [8]:
def estimate(age,m,c):
  return m*age + c

In [9]:
def try_estimates(m,c):
  ages=nonsmoker.age
  target=nonsmoker.charges
  estimated_charges = estimate(ages,m,c)

  plt.plot(ages,estimated_charges,'r')
  plt.scatter(x=ages,y=target)
  plt.xlabel=('age')
  plt.ylabel=('charges')
  plt.legend(['Estimate','Actual'])

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error as rmse
input,target=nonsmoker[['age','bmi']],nonsmoker[['charges']]
model=LinearRegression().fit(input,target)

In [12]:
predictions=model.predict(input)
predictions

array([[2749.08516308],
       [5412.40282772],
       [6673.94368635],
       ...,
       [2735.99553127],
       [2770.87763119],
       [3493.32334862]])

In [13]:
rmse(target,predictions)

4662.3128354612945

In [14]:
input,target=smokers[['age','bmi']],smokers[['charges']]
model=LinearRegression().fit(input,target)
predictions=model.predict(input)
predictions

array([[22814.8409452 ],
       [31950.08008214],
       [45409.21342133],
       [36385.92867933],
       [32590.350052  ],
       [38090.31188592],
       [34687.01818455],
       [37435.24431309],
       [39687.57444442],
       [50989.91391181],
       [37839.87292328],
       [30681.12453098],
       [36732.54286646],
       [46222.15151979],
       [27984.5326368 ],
       [24649.55981714],
       [15200.39458269],
       [19574.15430565],
       [20415.19213876],
       [37591.96196998],
       [37530.92875384],
       [22540.79339223],
       [37622.12205026],
       [36242.04549044],
       [39687.50035381],
       [21234.8299084 ],
       [15506.8107428 ],
       [36904.05812631],
       [23260.89454177],
       [44871.57295524],
       [25535.28682158],
       [34433.56042882],
       [23390.07733836],
       [11701.58774183],
       [23070.1877453 ],
       [26880.14728245],
       [33736.57708587],
       [22425.00993798],
       [25532.75881225],
       [18629.75079313],


In [16]:
rmse(target,predictions)

5722.782238884455

In [17]:
input,target=nonsmoker[['age','bmi','children']],nonsmoker[['charges']]
model=LinearRegression().fit(input,target)
predictions=model.predict(input)
predictions

array([[2724.94209163],
       [6535.13457204],
       [6065.27173951],
       ...,
       [2134.51524931],
       [2160.54349555],
       [2898.08585583]])

In [18]:
rmse(target,predictions)

4608.470405038247

In [19]:
input,target=batch1[['age','bmi','children']],batch1[['charges']]
model=LinearRegression().fit(input,target)
predictions=model.predict(input)
predictions

array([[ 6908.77753344],
       [ 9160.97706103],
       [12390.94691779],
       ...,
       [ 9640.92917145],
       [ 6691.39141657],
       [17377.08299024]])

In [20]:
rmse(target,predictions)

11355.317901125973

In [21]:
px.scatter(batch1,x='age',y='charges',color='smoker')

#Categorical

In [22]:
batch2['smokeroptions'] = batch2['smoker'].str.strip().str.lower()
batch2['smokeroptions'] = batch2['smoker'].map({'yes': 1, 'no': 0})
batch2

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smokeroptions  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
1333              0  
1334              0  
1335              0  
1336              0  
1337              1  

[1338 rows x 8 columns]

In [23]:
batch2['smokeroptions'].corr(batch2['charges'])

np.float64(0.7872514304984779)

In [24]:
input,target=batch2[['age','bmi','children','smokeroptions']],batch2[['charges']]
model=LinearRegression().fit(input,target)
predictions=model.predict(input)
predictions

array([[25587.42524891],
       [ 3880.94594512],
       [ 7158.62006921],
       ...,
       [ 4398.7459491 ],
       [ 1615.83647369],
       [36793.67069541]])

In [25]:
rmse(target,predictions)

6056.439217188081

In [26]:
batch2['sexoptions'] = batch2['sex'].str.strip().str.lower()
batch2['sexoptions'] = batch2['sex'].map({'male': 1, 'female': 0})
batch2

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smokeroptions  sexoptions  
0                 1           0  
1                 0           1  
2                 0           1  
3                 0           1  
4                 0           1  
...             ...         ...  
1333              0           1  
1334              0           0  
1335              0           0  
1336              0           0  
1337              1           0  

[1338 rows x 9 columns]

In [27]:
input,target=batch2[['age','bmi','children','smokeroptions','sexoptions']],batch2[['charges']]
model=LinearRegression().fit(input,target)
predictions=model.predict(input)
predictions

array([[25661.85689486],
       [ 3818.77858262],
       [ 7096.73025538],
       ...,
       [ 4465.88909619],
       [ 1676.96948913],
       [36863.89250792]])

In [23]:
rmse(target,predictions)

6056.100708754546

In [28]:
batch2['sexoptions'].corr(batch2['charges'])

np.float64(0.05729206220202548)

In [31]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder().fit(batch2[['region']])
encoder.categories_

[array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]

In [35]:
onehot=encoder.transform(batch2[['region']]).toarray()
onehot

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [44]:
batch2['locations']=batch2['region'].str.strip().str.lower()
batch2['locations'] = batch2['region'].map({'southeast': 1, 'southwest': 2,'northeast':3,'northwest':4})
batch2

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smokeroptions  sexoptions  locations  
0                 1           0          2  
1                 0           1          1  
2                 0           1          1  
3                 0           1          4  
4                 0           1          4  
...             ...         ...        ...  
1333              0           1          4  
1334              0           0          3  
1335              0           0          1  
1336              0           0          2  
1337              1           0          4  

[1338 rows x 10 columns]

In [42]:
batch2[['region']]=onehot
batch2

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smokeroptions  sexoptions  
0                 1           0  
1                 0           1  
2                 0           1  
3                 0           1  
4                 0           1  
...             ...         ...  
1333              0           1  
1334              0           0  
1335              0           0  
1336              0           0  
1337              1           0  

[1338 rows x 9 columns]

In [40]:
batch2

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smokeroptions  sexoptions  
0                 1           0  
1                 0           1  
2                 0           1  
3                 0           1  
4                 0           1  
...             ...         ...  
1333              0           1  
1334              0           0  
1335              0           0  
1336              0           0  
1337              1           0  

[1338 rows x 9 columns]

In [50]:
from sklearn.linear_model import LinearRegression

input = batch2[['age', 'bmi', 'children', 'smokeroptions', 'sexoptions', 'locations']]
target = batch2[['charges']]

model = LinearRegression()
model.fit(input, target)

predictions = model.predict(input)

print(predictions)


[[25542.57443639]
 [ 3438.4424626 ]
 [ 6685.32133654]
 ...
 [ 4137.08001864]
 [ 1481.70019193]
 [37325.22210761]]


In [51]:
rmse(target,predictions)

6047.417322694157

In [52]:
model.coef_

array([[  256.96796596,   337.0245187 ,   468.35404686, 23867.05868713,
         -128.95608532,   297.83720698]])

In [53]:
model.intercept_

array([-13205.53408956])

In [56]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
numeric_cols=['age','bmi','children']
scaler.fit(batch2[numeric_cols])
scaler.mean_

array([39.20702541, 30.66339686,  1.09491779])

In [57]:
scaler.var_

array([197.25385199,  37.16008997,   1.45212664])

In [58]:
scaled=scaler.transform(batch2[numeric_cols])
scaled

array([[-1.43876426, -0.45332   , -0.90861367],
       [-1.50996545,  0.5096211 , -0.07876719],
       [-0.79795355,  0.38330685,  1.58092576],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367],
       [-1.29636188, -0.79781341, -0.90861367],
       [ 1.55168573, -0.26138796, -0.90861367]])